spring.application.name=servicio-citas
server.port=8081
spring.datasource.url=jdbc:h2:mem:citasdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Servicios usados por la comunicacion sincrona HTTP.
piedrazul.servicios.pacientes-url=http://localhost:8082
piedrazul.servicios.especialistas-url=http://localhost:8083

# Comunicacion asincrona tipo BookingGym con RabbitMQ.
# Queda desactivada por defecto para no afectar el arranque del proyecto si no hay broker.
piedrazul.async.enabled=false
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
